openapi: 3.0.4
info:
  title: Word Pronunciation
  description: Word Pronunciation is a simple tool for getting the pronunciation of a word. It returns the pronunciation of the word provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/wordpronunciation:
    get:
      summary: Get Word Pronunciation
      description: Word Pronunciation is a simple tool for getting the pronunciation of a word. It returns the pronunciation of the word provided.
      operationId: wordpronunciation
      parameters:
      - name: word
        in: query
        schema:
          type: string
        required: true
        description: The word to get the pronunciation of
        example: hello
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  word: hello
                  pronounciation: HH AH0 L OW1
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
